version: "3"

volumes:
  poet-shared:

services:

  validator-2:
    container_name: validator-2
    build:
      context: docker/validator
    volumes:
      - poet-shared:/poet-shared
    environment:
      validator: validator-2
      validator_seed: boot-node-validator
    command: bash start.sh
    networks:
      - main-net

  poet-engine-2:
    container_name: poet-engine-2
    build:
      context: docker/poet-engine
    environment:
      validator: validator-2
    volumes:
      - poet-shared:/poet-shared
    command: bash start.sh
    networks:
      - main-net

  rest-api-2:
    container_name: rest-api-2
    build:
      context: docker/rest-api
    environment:
      validator: validator-2
      id: 2
    depends_on:
      - validator-2
    networks:
      - main-net

  settings-tp-2:
    container_name: settings-tp-2
    build:
      context: docker/settings-tp
    environment:
      validator: validator-2
    depends_on:
      - validator-2
    networks:
      - main-net

  identity-tp-2:
    container_name: identity-tp-2
    build:
      context: docker/identity-tp
    environment:
      validator: validator-2
    networks:
      - main-net

  intkey-tp-2:
    container_name: intkey-tp-2
    build:
      context: docker/intkey-tp
    environment:
      validator: validator-2
    networks:
      - main-net

  bchainca-tp-2:
    container_name: bchainca-tp-2
    build:
      context: docker/bchainca-tp
    environment:
      validator: validator-2
    depends_on:
      - validator-2
    networks:
      - main-net

  poet-validator-registry-tp-2:
    container_name: poet-validator-registry-tp-2
    build:
      context: docker/poet-validator-registry-tp
    environment:
      validator: validator-2
    depends_on:
      - validator-2
    networks:
      - main-net

networks:
  main-net:
    external: true
