version: "3"

services:

  client:
    container_name: sawtooth-sc-client
    build:
      context: client
      dockerfile: ./Dockerfile 
    networks:
      - benchmark-starter_main-net

networks: 
  benchmark-starter_main-net:
    external: true
